### ISSUE TITLE
Files for common reference go into main processed folder

### ISSUE THREAD

**Issue by aecker** [atlab/sessions#10]
# Problem
The files containing the common reference (used for Utah arrays and, more recently, silicon probes) currently go into the main processing folder `/processed/<subject>/<date>/` instead of the subfolder for the spike detection method: `/processed/<subject>/<date>/spikes/<detect_method_name>/`. 

This may create problems when spikes are detected with multiple different methods that differ in the way they extract or store the common reference, since they will overwrite each others' common reference files. 

# Expected issues
It should not affect the extracted spikes in any way, so long as the different spike detection processes do not run concurrently. The only effect is that the files containing the common reference (`ref%d`) will be overwritten by the most recently run version.

# Suggested fix
keep as is for Utah array code to maintain backwards compatibility, but change the behavior to correctly store the common reference in the proper subfolder for silicon probes.

**Comment by gdenfield** [comment]
1) In order to create the appropriate file path for saving the ref in the proper subfolder, I need to get information into the extract_common_reference function pertaining to which detection method to use, and I'm trying to think of the best way to do this. One option is passing the detect 'key' as an input to the function, since it has detect_method subfield, but this change would have to be made in several files all the way upstream to the spike detection call back function(s) in processSet, and so specifically for each of the spikes*.m files we have. Though a simple change it involves changing quite a few files so isn't as clean as I'd like. I don't know of a good way to infer the detection method given that the only inputs to the relevant functions we use downstream of processSet are file paths basically, and since our basic acq.Ephys PK could be associated with a number of methods. Any thoughts?

2) Something odd happened when I altered the extract_common_reference (ECR) file. I first created a new branch called refupdate using my specific git bash on at-detect, while on this branch (yes I really did have this branch checked-out) I began to edit the ECR file. I saved the file but did not commit or stage to commit these changes (I was not at a satisfactory stopping point where I'd done anything productive yet). However, I subsequently checked out the master branch, and after doing so, my ERC file did not revert to the version on the remote master and remains the edited version. This was unexpected, I was hoping to revert to the original version, any ideas what might have gone wrong?

**Comment by aecker** [comment]
1) From looking into `extract_common_reference.m` the file should go into the same folder where the raw data files reside. Although it's confusing me, since I thought I had seen ref%d files in `/processed/subject/date`, I think it's probably fine to keep it like that. After spike detection we don't need the common_ref file anymore and if we do want to re-detect them we need the raw data anyway and can re-extract it.

2) Did you check out master in the main directory of at-core or in the subfolder ephys-preprocessing? The effect will not be the same, since in the main directory you check out the master branch of at-core and in the subfolder you check out the master branch of ephys-preprocessing, which is a submodule. In the former case nothing should change unless you specify some recursive option, which would update the submodules as well. In the latter case it should actually cause an error since you have uncommitted local changes.

**Comment by gdenfield** [comment]
I checked it out in the subfolder ephys-preprocessing but didn't get any error

**Comment by aecker** [comment]
Turns out this is expected behavior. If the changes you made are not being overwritten by checking out a different branch (i.e. if in the modified file is identical in the two branches) then you can switch between branches without committing your changes. Only if the file you modified is different, and therefore your changes would be overwritten by checking out a new branch, will git complain.

**Comment by gdenfield** [comment]
Closing issue: we decided not to alter the location of the saved file but instead fixed the case where the ref file was being copied to the processed folder erroneously rather than deleted from the temp drive with the raw data copies.
