### ISSUE TITLE
If clause within tetrode case in KalmanAutomatic

### ISSUE THREAD

**Issue by gdenfield** [atlab/sessions#4]
Currently it looks like we have a weird implementation for single electrode recordings within the tetrode case for the Kalman sorting model. 
With the way we are trying to implement a lookup table for sorting params for different array types this could present some backwards compatibility issues given the different way most cases would now be handled versus the way the single electrode case is handled.
Granted, I know of no one currently using or analyzing single electrode data but I wanted to bring this to everyone's attention just in case someone with more knowledge sees this as a problem.

**Comment by aecker** [comment]
This weird implementation is indeed to handle the reference tetrodes on chronic tetrode drives. These have only one channel connected (since they originally are supposed to be used as references). However, sometimes they were actually in the brain an picking up real spikes and never used as actual references. In those cases, we wanted to process them to analyze those neurons as well.

I put the special treatment of references channels back in place in f99b97738f6cab3c880d6e2b309b4fe195c5881d. This means for those few cases the parameters are hardcoded and not taken from `sort.KalmanParams`. It's not pretty, but currently the only solution I can see without creating a ton of code overhead.
